# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WorkSpace/Vivado/ip_repo/IMAGE_DATA_CONVERTER_1.0/src/bram_buffer/bram_buffer.xci
# IP: The module: 'bram_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/Vivado/ip_repo/IMAGE_DATA_CONVERTER_1.0/src/bram_buffer/bram_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/WorkSpace/Vivado/ip_repo/IMAGE_DATA_CONVERTER_1.0/src/bram_buffer/bram_buffer.xci
# IP: The module: 'bram_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WorkSpace/Vivado/ip_repo/IMAGE_DATA_CONVERTER_1.0/src/bram_buffer/bram_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
