# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/zedboard.xdc

# Block Designs: bd/OV_HDMI/OV_HDMI.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI || ORIG_REF_NAME==OV_HDMI} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_processing_system7_0_0/OV_HDMI_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_processing_system7_0_0 || ORIG_REF_NAME==OV_HDMI_processing_system7_0_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_0/OV_HDMI_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_axi_gpio_0_0 || ORIG_REF_NAME==OV_HDMI_axi_gpio_0_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_ps7_0_axi_periph_0/OV_HDMI_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_ps7_0_axi_periph_0 || ORIG_REF_NAME==OV_HDMI_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_rst_ps7_0_150M_0/OV_HDMI_rst_ps7_0_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_rst_ps7_0_150M_0 || ORIG_REF_NAME==OV_HDMI_rst_ps7_0_150M_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_HDMI_AXI_FULL_0_0/OV_HDMI_HDMI_AXI_FULL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_HDMI_AXI_FULL_0_0 || ORIG_REF_NAME==OV_HDMI_HDMI_AXI_FULL_0_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_HDMI_AXI_FULL_0_0/src/bram_cacheline_1/bram_cacheline.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_cacheline || ORIG_REF_NAME==bram_cacheline} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/OV_HDMI_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_axi_smc_0 || ORIG_REF_NAME==OV_HDMI_axi_smc_0} -quiet] -quiet

# Block Designs: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/bd_693e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_10/bd_693e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_19/bd_693e_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_25/bd_693e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_31/bd_693e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_26/bd_693e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_27/bd_693e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_28/bd_693e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_29/bd_693e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_30/bd_693e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_20/bd_693e_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_21/bd_693e_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_22/bd_693e_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_23/bd_693e_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_24/bd_693e_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_16/bd_693e_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_17/bd_693e_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_18/bd_693e_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_11/bd_693e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_12/bd_693e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_13/bd_693e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_14/bd_693e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_15/bd_693e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_7/bd_693e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_8/bd_693e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_9/bd_693e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_2/bd_693e_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_3/bd_693e_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_4/bd_693e_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_5/bd_693e_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_6/bd_693e_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_0/bd_693e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_1/bd_693e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/OV_HDMI/ip/OV_HDMI_xbar_0/OV_HDMI_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_xbar_0 || ORIG_REF_NAME==OV_HDMI_xbar_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_selectio_wiz_0_0/OV_HDMI_selectio_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_selectio_wiz_0_0 || ORIG_REF_NAME==OV_HDMI_selectio_wiz_0_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_mipi_interface_0_0/OV_HDMI_mipi_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_mipi_interface_0_0 || ORIG_REF_NAME==OV_HDMI_mipi_interface_0_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_IMAGE_DATA_CONVERTER_0_0/OV_HDMI_IMAGE_DATA_CONVERTER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_IMAGE_DATA_CONVERTER_0_0 || ORIG_REF_NAME==OV_HDMI_IMAGE_DATA_CONVERTER_0_0} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_IMAGE_DATA_CONVERTER_0_0/src/bram_cacheline_cam/bram_cacheline_cam.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_cacheline_cam || ORIG_REF_NAME==bram_cacheline_cam} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_IMAGE_DATA_CONVERTER_0_0/src/bram_buffer/bram_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_buffer || ORIG_REF_NAME==bram_buffer} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_1/OV_HDMI_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_axi_gpio_0_1 || ORIG_REF_NAME==OV_HDMI_axi_gpio_0_1} -quiet] -quiet

# IP: bd/OV_HDMI/ip/OV_HDMI_auto_pc_0/OV_HDMI_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OV_HDMI_auto_pc_0 || ORIG_REF_NAME==OV_HDMI_auto_pc_0} -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_processing_system7_0_0/OV_HDMI_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OV_HDMI_processing_system7_0_0 || ORIG_REF_NAME==OV_HDMI_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_0/OV_HDMI_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OV_HDMI_axi_gpio_0_0 || ORIG_REF_NAME==OV_HDMI_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_0/OV_HDMI_axi_gpio_0_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_0/OV_HDMI_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OV_HDMI_axi_gpio_0_0 || ORIG_REF_NAME==OV_HDMI_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_rst_ps7_0_150M_0/OV_HDMI_rst_ps7_0_150M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OV_HDMI_rst_ps7_0_150M_0 || ORIG_REF_NAME==OV_HDMI_rst_ps7_0_150M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_rst_ps7_0_150M_0/OV_HDMI_rst_ps7_0_150M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OV_HDMI_rst_ps7_0_150M_0 || ORIG_REF_NAME==OV_HDMI_rst_ps7_0_150M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_HDMI_AXI_FULL_0_0/src/bram_cacheline_1/bram_cacheline_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_10/bd_693e_s00a2s_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_19/bd_693e_s01a2s_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_25/bd_693e_m00s2a_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_26/bd_693e_m00arn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_27/bd_693e_m00rn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_28/bd_693e_m00awn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_29/bd_693e_m00wn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_30/bd_693e_m00bn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_20/bd_693e_sarn_1_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_21/bd_693e_srn_1_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_22/bd_693e_sawn_1_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_23/bd_693e_swn_1_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_24/bd_693e_sbn_1_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_11/bd_693e_sarn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_12/bd_693e_srn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_13/bd_693e_sawn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_14/bd_693e_swn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_15/bd_693e_sbn_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_2/bd_693e_arsw_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_3/bd_693e_rsw_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_4/bd_693e_awsw_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_5/bd_693e_wsw_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_6/bd_693e_bsw_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_1/bd_693e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_1/bd_693e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_selectio_wiz_0_0/OV_HDMI_selectio_wiz_0_0_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_selectio_wiz_0_0/OV_HDMI_selectio_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OV_HDMI_selectio_wiz_0_0 || ORIG_REF_NAME==OV_HDMI_selectio_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_IMAGE_DATA_CONVERTER_0_0/src/bram_cacheline_cam/bram_cacheline_cam_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_IMAGE_DATA_CONVERTER_0_0/src/bram_buffer/bram_buffer_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_1/OV_HDMI_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OV_HDMI_axi_gpio_0_1 || ORIG_REF_NAME==OV_HDMI_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_1/OV_HDMI_axi_gpio_0_1_ooc.xdc

# XDC: bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_1/OV_HDMI_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==OV_HDMI_axi_gpio_0_1 || ORIG_REF_NAME==OV_HDMI_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/OV_HDMI/ip/OV_HDMI_auto_pc_0/OV_HDMI_auto_pc_0_ooc.xdc

# XDC: bd/OV_HDMI/OV_HDMI_ooc.xdc
