# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.cache/wt [current_project]
set_property parent.project_path D:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/WorkSpace/Vivado/ip_repo/color_bar_master_1.0
  d:/WorkSpace/Vivado/ip_repo/IMAGE_DATA_CONVERTER_1.0
  d:/WorkSpace/Vivado/ip_repo
} [current_project]
set_property ip_output_repo d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/hdl/OV_HDMI_wrapper.v
add_files D:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/OV_HDMI.bd
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_processing_system7_0_0/OV_HDMI_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_0/OV_HDMI_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_0/OV_HDMI_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_0/OV_HDMI_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_rst_ps7_0_150M_0/OV_HDMI_rst_ps7_0_150M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_rst_ps7_0_150M_0/OV_HDMI_rst_ps7_0_150M_0.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_HDMI_AXI_FULL_0_0/src/bram_cacheline_1/bram_cacheline_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_10/bd_693e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_19/bd_693e_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_25/bd_693e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_26/bd_693e_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_27/bd_693e_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_28/bd_693e_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_29/bd_693e_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_30/bd_693e_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_20/bd_693e_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_21/bd_693e_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_22/bd_693e_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_23/bd_693e_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_24/bd_693e_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_11/bd_693e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_12/bd_693e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_13/bd_693e_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_14/bd_693e_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_15/bd_693e_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_2/bd_693e_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_3/bd_693e_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_4/bd_693e_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_5/bd_693e_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_6/bd_693e_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_1/bd_693e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/bd_0/ip/ip_1/bd_693e_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_selectio_wiz_0_0/OV_HDMI_selectio_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_selectio_wiz_0_0/OV_HDMI_selectio_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_IMAGE_DATA_CONVERTER_0_0/src/bram_cacheline_cam/bram_cacheline_cam_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_IMAGE_DATA_CONVERTER_0_0/src/bram_buffer/bram_buffer_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_1/OV_HDMI_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_1/OV_HDMI_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_axi_gpio_0_1/OV_HDMI_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/ip/OV_HDMI_auto_pc_0/OV_HDMI_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/sources_1/bd/OV_HDMI/OV_HDMI_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/zedboard.xdc
set_property used_in_implementation false [get_files D:/WorkSpace/Vivado/OV_HDMI/OV_HDMI.srcs/zedboard.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top OV_HDMI_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef OV_HDMI_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file OV_HDMI_wrapper_utilization_synth.rpt -pb OV_HDMI_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
