set_property SRC_FILE_INFO {cfile:d:/WorkSpace/Vivado/HDMI_AXI_FULL/HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_processing_system7_0_0/HDMI_AXI_FULL_processing_system7_0_0.xdc rfile:../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_processing_system7_0_0/HDMI_AXI_FULL_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:HDMI_AXI_FULL_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/WorkSpace/Vivado/HDMI_AXI_FULL/HDMI_AXI_FULL.srcs/zedboard.xdc rfile:../../../HDMI_AXI_FULL.srcs/zedboard.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:3 order:LATE scoped_inst:{HDMI_AXI_FULL_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:4 order:LATE scoped_inst:{HDMI_AXI_FULL_i/axi_smc/inst/s00_nodes/s00_aw_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:5 order:LATE scoped_inst:{HDMI_AXI_FULL_i/axi_smc/inst/s00_nodes/s00_b_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:6 order:LATE scoped_inst:{HDMI_AXI_FULL_i/axi_smc/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:7 order:LATE scoped_inst:{HDMI_AXI_FULL_i/axi_smc/inst/s00_nodes/s00_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.19998
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C14" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B11" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N7" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M7" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R5" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F3" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W2" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G1" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U1" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA3" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA2" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P6" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N4" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M6" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L6" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L7" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J6" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J7" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K5" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K6" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C9" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F7" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports hdmi_clk]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[0]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[1]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[2]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[3]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[4]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[5]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[6]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[7]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[8]}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[9]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[10]}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[11]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[12]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[13]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[14]}]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {hdmi_d[15]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports hdmi_de]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports hdmi_hsync]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33 SLEW FAST} [get_ports hdmi_vsync]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS33} [get_ports hdmi_scl]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports hdmi_sda]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P16   IOSTANDARD LVCMOS25} [get_ports button[0]]      ; ## BTNC
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R16   IOSTANDARD LVCMOS25} [get_ports button[1]]      ; ## BTND
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R18   IOSTANDARD LVCMOS25} [get_ports reset]          ; ## BTNR
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports {led_tri_o[0]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports {led_tri_o[1]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports {led_tri_o[2]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports {led_tri_o[3]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/hdmi_clk]]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list HDMI_AXI_FULL_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[0]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[1]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[2]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[3]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[4]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[5]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[6]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[7]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[8]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[9]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[10]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/h_counter[11]}]]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[0]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[1]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[2]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[3]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[4]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[5]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[6]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[7]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[8]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[9]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[10]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[11]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[12]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[13]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[14]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[15]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[16]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[17]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[18]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[19]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[20]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[21]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[22]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[23]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[24]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[25]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[26]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[27]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[28]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[29]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[30]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/dina[31]}]]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[0]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[1]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[2]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[3]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[4]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[5]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[6]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[7]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[8]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[9]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[10]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/v_counter[11]}]]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[0]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[1]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[2]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[3]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[4]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[5]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[6]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[7]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[8]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[9]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[10]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[11]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[12]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[13]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[14]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_d[15]}]]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[0]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[1]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[2]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[3]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[4]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[5]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[6]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[7]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[8]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[9]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[10]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[11]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[12]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[13]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[14]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[15]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[16]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[17]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[18]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[19]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[20]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[21]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[22]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[23]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[24]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[25]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[26]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[27]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[28]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[29]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[30]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rdata[31]}]]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[0]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[1]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[2]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[3]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[4]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[5]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[6]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[7]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[8]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[9]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[10]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[11]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[12]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[13]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[14]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[15]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[16]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[17]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[18]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[19]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[20]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[21]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[22]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[23]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[24]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[25]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[26]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[27]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[28]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[29]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[30]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RDATA[31]}]]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[0]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[1]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[2]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[3]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[4]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[5]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[6]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[7]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[8]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[9]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[10]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[11]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[12]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[13]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[14]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[15]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[16]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[17]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[18]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[19]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[20]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[21]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[22]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[23]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[24]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[25]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[26]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[27]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[28]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[29]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[30]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/axi_araddr[31]}]]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[0]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[1]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[2]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[3]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[4]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[5]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[6]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[7]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[8]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[9]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[10]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[11]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[12]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[13]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[14]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[15]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[16]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[17]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[18]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[19]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[20]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[21]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[22]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[23]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[24]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[25]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[26]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[27]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[28]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[29]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[30]} {HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_AWADDR[31]}]]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_de]]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_hsync]]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_scl]]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_sda]]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/hdmi_vsync]]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/init_txn_pulse]]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_arready]]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_arvalid]]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rlast]]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rready]]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/m00_axi_rvalid]]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_ARREADY]]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_ARVALID]]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RLAST]]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RREADY]]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/M_AXI_RVALID]]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/reads_done]]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/start_single_burst_read]]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/txn_request]]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list HDMI_AXI_FULL_i/HDMI_AXI_FULL_0/inst/HDMI_AXI_FULL_v2_0_M00_AXI_inst/hdmi01/wea]]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets hdmi_clk_OBUF]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
