vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/xpm
vlib questa_lib/msim/blk_mem_gen_v8_4_1
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/smartconnect_v1_0
vlib questa_lib/msim/axi_protocol_checker_v2_0_3
vlib questa_lib/msim/axi_vip_v1_1_3
vlib questa_lib/msim/processing_system7_vip_v1_0_5
vlib questa_lib/msim/axi_lite_ipif_v3_0_4
vlib questa_lib/msim/lib_cdc_v1_0_2
vlib questa_lib/msim/interrupt_control_v3_1_4
vlib questa_lib/msim/axi_gpio_v2_0_19
vlib questa_lib/msim/xlconstant_v1_1_5
vlib questa_lib/msim/proc_sys_reset_v5_0_12
vlib questa_lib/msim/generic_baseblocks_v2_1_0
vlib questa_lib/msim/axi_register_slice_v2_1_17
vlib questa_lib/msim/fifo_generator_v13_2_2
vlib questa_lib/msim/axi_data_fifo_v2_1_16
vlib questa_lib/msim/axi_crossbar_v2_1_18
vlib questa_lib/msim/axi_protocol_converter_v2_1_17

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap xpm questa_lib/msim/xpm
vmap blk_mem_gen_v8_4_1 questa_lib/msim/blk_mem_gen_v8_4_1
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 questa_lib/msim/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_3 questa_lib/msim/axi_protocol_checker_v2_0_3
vmap axi_vip_v1_1_3 questa_lib/msim/axi_vip_v1_1_3
vmap processing_system7_vip_v1_0_5 questa_lib/msim/processing_system7_vip_v1_0_5
vmap axi_lite_ipif_v3_0_4 questa_lib/msim/axi_lite_ipif_v3_0_4
vmap lib_cdc_v1_0_2 questa_lib/msim/lib_cdc_v1_0_2
vmap interrupt_control_v3_1_4 questa_lib/msim/interrupt_control_v3_1_4
vmap axi_gpio_v2_0_19 questa_lib/msim/axi_gpio_v2_0_19
vmap xlconstant_v1_1_5 questa_lib/msim/xlconstant_v1_1_5
vmap proc_sys_reset_v5_0_12 questa_lib/msim/proc_sys_reset_v5_0_12
vmap generic_baseblocks_v2_1_0 questa_lib/msim/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_17 questa_lib/msim/axi_register_slice_v2_1_17
vmap fifo_generator_v13_2_2 questa_lib/msim/fifo_generator_v13_2_2
vmap axi_data_fifo_v2_1_16 questa_lib/msim/axi_data_fifo_v2_1_16
vmap axi_crossbar_v2_1_18 questa_lib/msim/axi_crossbar_v2_1_18
vmap axi_protocol_converter_v2_1_17 questa_lib/msim/axi_protocol_converter_v2_1_17

vlog -work xilinx_vip -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93 \
"D:/Program/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work blk_mem_gen_v8_4_1 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_HDMI_AXI_FULL_0_0/src/bram_cacheline_1/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_HDMI_AXI_FULL_0_0/src/bram_cacheline_1/sim/bram_cacheline.v" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/fa5d/hdl/HDMI_AXI_FULL_v2_0_M00_AXI.v" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/fa5d/hdl/HDMI_AXI_FULL_v2_0_S01_AXI.v" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/fa5d/src/i2c_sender.v" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/fa5d/src/zynq_hdmi_1080p.v" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/fa5d/hdl/HDMI_AXI_FULL_v2_0.v" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_HDMI_AXI_FULL_0_0/sim/HDMI_AXI_FULL_HDMI_AXI_FULL_0_0.v" \

vlog -work axi_infrastructure_v1_1_0 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_3 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_3 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_5 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_processing_system7_0_0/sim/HDMI_AXI_FULL_processing_system7_0_0.v" \

vcom -work axi_lite_ipif_v3_0_4 -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work interrupt_control_v3_1_4 -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_19 -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_gpio_0_0/sim/HDMI_AXI_FULL_axi_gpio_0_0.vhd" \

vlog -work xil_defaultlib -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/sim/bd_98c6.v" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_5/sim/bd_98c6_s00a2s_0.sv" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_11/sim/bd_98c6_m00s2a_0.sv" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_12/sim/bd_98c6_m00e_0.sv" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_6/sim/bd_98c6_sarn_0.sv" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_7/sim/bd_98c6_srn_0.sv" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_8/sim/bd_98c6_sawn_0.sv" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_9/sim/bd_98c6_swn_0.sv" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_10/sim/bd_98c6_sbn_0.sv" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_2/sim/bd_98c6_s00mmu_0.sv" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_3/sim/bd_98c6_s00tr_0.sv" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_4/sim/bd_98c6_s00sic_0.sv" \

vlog -work xlconstant_v1_1_5 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_0/sim/bd_98c6_one_0.v" \

vcom -work proc_sys_reset_v5_0_12 -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_1/sim/bd_98c6_psr_aclk_0.vhd" \

vlog -work xil_defaultlib -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/sim/HDMI_AXI_FULL_axi_smc_0.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_rst_ps7_0_150M_0/sim/HDMI_AXI_FULL_rst_ps7_0_150M_0.vhd" \

vlog -work generic_baseblocks_v2_1_0 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_17 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_2 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_2 -64 -93 \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_2 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axi_data_fifo_v2_1_16 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_18 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_xbar_0/sim/HDMI_AXI_FULL_xbar_0.v" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/sim/HDMI_AXI_FULL.v" \

vlog -work axi_protocol_converter_v2_1_17 -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/ec67/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/5bb9/hdl/verilog" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/70fd/hdl" "+incdir+../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ipshared/f90c/hdl/verilog" "+incdir+D:/Program/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../HDMI_AXI_FULL.srcs/sources_1/bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_auto_pc_0/sim/HDMI_AXI_FULL_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

