# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard.xdc

# Block Designs: bd/HDMI_AXI_LITE/HDMI_AXI_LITE.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE || ORIG_REF_NAME==HDMI_AXI_LITE} -quiet] -quiet

# IP: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_HDMI_AXI_LITE_0_0/HDMI_AXI_LITE_HDMI_AXI_LITE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_HDMI_AXI_LITE_0_0 || ORIG_REF_NAME==HDMI_AXI_LITE_HDMI_AXI_LITE_0_0} -quiet] -quiet

# IP: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_HDMI_AXI_LITE_0_0/src/pic_rom/pic_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pic_rom || ORIG_REF_NAME==pic_rom} -quiet] -quiet

# IP: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_processing_system7_0_0/HDMI_AXI_LITE_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_processing_system7_0_0 || ORIG_REF_NAME==HDMI_AXI_LITE_processing_system7_0_0} -quiet] -quiet

# IP: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_ps7_0_axi_periph_0/HDMI_AXI_LITE_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_ps7_0_axi_periph_0 || ORIG_REF_NAME==HDMI_AXI_LITE_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_rst_ps7_0_100M_0/HDMI_AXI_LITE_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_rst_ps7_0_100M_0 || ORIG_REF_NAME==HDMI_AXI_LITE_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_axi_gpio_0_0/HDMI_AXI_LITE_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_axi_gpio_0_0 || ORIG_REF_NAME==HDMI_AXI_LITE_axi_gpio_0_0} -quiet] -quiet

# IP: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_xbar_0/HDMI_AXI_LITE_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_xbar_0 || ORIG_REF_NAME==HDMI_AXI_LITE_xbar_0} -quiet] -quiet

# IP: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_auto_pc_0/HDMI_AXI_LITE_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_auto_pc_0 || ORIG_REF_NAME==HDMI_AXI_LITE_auto_pc_0} -quiet] -quiet

# XDC: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_HDMI_AXI_LITE_0_0/src/pic_rom/pic_rom_ooc.xdc

# XDC: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_processing_system7_0_0/HDMI_AXI_LITE_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_processing_system7_0_0 || ORIG_REF_NAME==HDMI_AXI_LITE_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_rst_ps7_0_100M_0/HDMI_AXI_LITE_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_rst_ps7_0_100M_0 || ORIG_REF_NAME==HDMI_AXI_LITE_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_rst_ps7_0_100M_0/HDMI_AXI_LITE_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_rst_ps7_0_100M_0 || ORIG_REF_NAME==HDMI_AXI_LITE_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_axi_gpio_0_0/HDMI_AXI_LITE_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_axi_gpio_0_0 || ORIG_REF_NAME==HDMI_AXI_LITE_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_axi_gpio_0_0/HDMI_AXI_LITE_axi_gpio_0_0_ooc.xdc

# XDC: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_axi_gpio_0_0/HDMI_AXI_LITE_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_LITE_axi_gpio_0_0 || ORIG_REF_NAME==HDMI_AXI_LITE_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HDMI_AXI_LITE/ip/HDMI_AXI_LITE_auto_pc_0/HDMI_AXI_LITE_auto_pc_0_ooc.xdc

# XDC: bd/HDMI_AXI_LITE/HDMI_AXI_LITE_ooc.xdc
