# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/WorkSpace/Vivado/HDMI_AXI_FULL/HDMI_AXI_FULL.srcs/zedboard.xdc

# Block Designs: bd/HDMI_AXI_FULL/HDMI_AXI_FULL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL || ORIG_REF_NAME==HDMI_AXI_FULL} -quiet] -quiet

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_HDMI_AXI_FULL_0_0/HDMI_AXI_FULL_HDMI_AXI_FULL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_HDMI_AXI_FULL_0_0 || ORIG_REF_NAME==HDMI_AXI_FULL_HDMI_AXI_FULL_0_0} -quiet] -quiet

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_HDMI_AXI_FULL_0_0/src/bram_cacheline_1/bram_cacheline.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_cacheline || ORIG_REF_NAME==bram_cacheline} -quiet] -quiet

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_processing_system7_0_0/HDMI_AXI_FULL_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_processing_system7_0_0 || ORIG_REF_NAME==HDMI_AXI_FULL_processing_system7_0_0} -quiet] -quiet

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_gpio_0_0/HDMI_AXI_FULL_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_axi_gpio_0_0 || ORIG_REF_NAME==HDMI_AXI_FULL_axi_gpio_0_0} -quiet] -quiet

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/HDMI_AXI_FULL_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_axi_smc_0 || ORIG_REF_NAME==HDMI_AXI_FULL_axi_smc_0} -quiet] -quiet

# Block Designs: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/bd_98c6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_5/bd_98c6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_11/bd_98c6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_12/bd_98c6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_6/bd_98c6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_7/bd_98c6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_8/bd_98c6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_9/bd_98c6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_10/bd_98c6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_2/bd_98c6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_3/bd_98c6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_4/bd_98c6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_0/bd_98c6_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_1/bd_98c6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_rst_ps7_0_150M_0/HDMI_AXI_FULL_rst_ps7_0_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_rst_ps7_0_150M_0 || ORIG_REF_NAME==HDMI_AXI_FULL_rst_ps7_0_150M_0} -quiet] -quiet

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_ps7_0_axi_periph_0/HDMI_AXI_FULL_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_ps7_0_axi_periph_0 || ORIG_REF_NAME==HDMI_AXI_FULL_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_xbar_0/HDMI_AXI_FULL_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_xbar_0 || ORIG_REF_NAME==HDMI_AXI_FULL_xbar_0} -quiet] -quiet

# IP: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_auto_pc_0/HDMI_AXI_FULL_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_auto_pc_0 || ORIG_REF_NAME==HDMI_AXI_FULL_auto_pc_0} -quiet] -quiet

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_HDMI_AXI_FULL_0_0/src/bram_cacheline_1/bram_cacheline_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_processing_system7_0_0/HDMI_AXI_FULL_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_processing_system7_0_0 || ORIG_REF_NAME==HDMI_AXI_FULL_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_gpio_0_0/HDMI_AXI_FULL_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_axi_gpio_0_0 || ORIG_REF_NAME==HDMI_AXI_FULL_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_gpio_0_0/HDMI_AXI_FULL_axi_gpio_0_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_gpio_0_0/HDMI_AXI_FULL_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_axi_gpio_0_0 || ORIG_REF_NAME==HDMI_AXI_FULL_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_5/bd_98c6_s00a2s_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_11/bd_98c6_m00s2a_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_6/bd_98c6_sarn_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_7/bd_98c6_srn_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_8/bd_98c6_sawn_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_9/bd_98c6_swn_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_10/bd_98c6_sbn_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_1/bd_98c6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/bd_0/ip/ip_1/bd_98c6_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_axi_smc_0/ooc.xdc

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_rst_ps7_0_150M_0/HDMI_AXI_FULL_rst_ps7_0_150M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_rst_ps7_0_150M_0 || ORIG_REF_NAME==HDMI_AXI_FULL_rst_ps7_0_150M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_rst_ps7_0_150M_0/HDMI_AXI_FULL_rst_ps7_0_150M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==HDMI_AXI_FULL_rst_ps7_0_150M_0 || ORIG_REF_NAME==HDMI_AXI_FULL_rst_ps7_0_150M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/HDMI_AXI_FULL/ip/HDMI_AXI_FULL_auto_pc_0/HDMI_AXI_FULL_auto_pc_0_ooc.xdc

# XDC: bd/HDMI_AXI_FULL/HDMI_AXI_FULL_ooc.xdc
